### ISSUE TITLE
Pandoc support

### ISSUE THREAD

**Issue by m42e** [mafgwo/stackedit-plus#2]
Is there a reason panda support is not available?
Thanks.

**Comment by mafgwo** [comment]
Because there are many system packages that need to be dependent on when building Docker images with Pandoc, I have commented them out. You can find the corresponding code and release it, but after releasing it, you need to solve the problem of dependent system packages on your own.
After I have refactored all the code and achieved front-end and back-end separation, I will reconsider restoring Pandoc.

**Comment by m42e** [comment]
ok, understood
